<%@ include file="/WEB-INF/jsp/includes/taglibs.jsp" %>

var fb_lang = {
    // Main menu
        save            : '<fmt:message key="formbuilder.save"/>'
    ,   preview         : '<fmt:message key="formbuilder.preview"/>'
    ,   mobilePreview   : '<fmt:message key="formbuilder.mobilePreview"/>'
    ,   html            : '<fmt:message key="formbuilder.html"/>'
    ,   exit            : '<fmt:message key="formbuilder.exit"/>'
    ,   undo            : '<fmt:message key="formbuilder.undo"/>'
    ,   load            : '<fmt:message key="formbuilder.load"/>'
    // Widgets
    ,   text            : '<fmt:message key="formbuilder.text"/>'
    ,   readonlytext    : '<fmt:message key="formbuilder.readonlytext"/>'
    ,   textarea        : '<fmt:message key="formbuilder.textarea"/>'
    ,   readonlytextarea: '<fmt:message key="formbuilder.readonlytextarea"/>'
    ,   select          : '<fmt:message key="formbuilder.select"/>'
    ,   checkbox        : '<fmt:message key="formbuilder.checkbox"/>'
    ,   datepicker      : '<fmt:message key="formbuilder.datepicker"/>'
    ,   radio           : '<fmt:message key="formbuilder.radio"/>'
    ,   subform         : '<fmt:message key="formbuilder.subform"/>'
    ,   file            : '<fmt:message key="formbuilder.file"/>'
    ,   grid            : '<fmt:message key="formbuilder.grid"/>'
    ,   htmleditor      : '<fmt:message key="formbuilder.htmleditor"/>'
    ,   fieldset        : '<fmt:message key="formbuilder.fieldset"/>'
    ,   hiddenfield     : '<fmt:message key="formbuilder.hiddenfield"/>'
    ,   customHtml      : '<fmt:message key="formbuilder.customHtml"/>'
    // Preview HTML
    ,   htmlpreview     : '<fmt:message key="formbuilder.htmlpreview"/>'
    // Validation
    ,   val_required    : '<fmt:message key="formbuilder.val_required"/>'
    ,   required_lab    : '<fmt:message key="formbuilder.required_lab"/>'
    ,   name_validation : '<fmt:message key="formbuilder.name_validation"/>'
    // UI flash messages
    ,   msg_widget_clic    : '<fmt:message key="formbuilder.msg_widget_clic"/>'
    ,   msg_is_required    : '<fmt:message key="formbuilder.msg_is_required"/>'
    ,   msg_not_required   : '<fmt:message key="formbuilder.msg_not_required"/>'
    ,   msg_err_del_opt    : '<fmt:message key="formbuilder.msg_err_del_opt"/>'
    ,   msg_save           : '<fmt:message key="formbuilder.msg_save"/>'
    ,   msg_err_load       : '<fmt:message key="formbuilder.msg_err_load"/>'
    ,   msg_ok_load        : '<fmt:message key="formbuilder.msg_ok_load"/>'
    ,   msg_confirm_fs_del : '<fmt:message key="formbuilder.msg_confirm_fs_del"/>'
    ,   msg_help           : '<fmt:message key="formbuilder.msg_help"/>'
    ,   msg_error_in_form  : '<fmt:message key="formbuilder.msg_error_in_form"/>'
    ,   msg_loading        : '<fmt:message key="formbuilder.msg_loading"/>'
    ,   msg_form_saved     : '<fmt:message key="formbuilder.msg_form_saved"/>'
    // UI
    ,   formtitle         : '<fmt:message key="formbuilder.formtitle"/>'
    ,   elements          : '<fmt:message key="formbuilder.elements"/>'
    , 	properties		  : '<fmt:message key="formbuilder.properties"/>'
    ,   element_add_new   : '<fmt:message key="formbuilder.element_add_new"/>'
    ,   clic_to_edit      : '<fmt:message key="formbuilder.clic_to_edit"/>'
    ,   clic_del_row      : '<fmt:message key="formbuilder.clic_del_row"/>'
    ,   clic_del_fieldset : '<fmt:message key="formbuilder.clic_del_fieldset"/>'
    ,   clic_set_req      : '<fmt:message key="formbuilder.clic_set_req"/>'
    ,   clic_edit_row     : '<fmt:message key="formbuilder.clic_edit_row"/>'
    ,   clic_disable_row  : '<fmt:message key="formbuilder.clic_disable_row"/>'
    ,   clic_moveup_row   : '<fmt:message key="formbuilder.clic_moveup_row"/>'
    ,   clic_movedown_row : '<fmt:message key="formbuilder.clic_movedown_row"/>'
    ,   fieldset_mode     : '<fmt:message key="formbuilder.fieldset_mode"/>'
    ,   fieldset_mode_normal : '<fmt:message key="formbuilder.fieldset_mode_normal"/>'
    ,   fieldset_mode_tab    : '<fmt:message key="formbuilder.fieldset_mode_tab"/>'
    // Labels
    ,   name            : '<fmt:message key="formbuilder.name"/>'
    ,   description     : '<fmt:message key="formbuilder.description"/>'
    ,   fieldset_legend : '<fmt:message key="formbuilder.fieldset_legend"/>'
    ,   tab_title       : '<fmt:message key="formbuilder.tab_title"/>'
    // Widgets instructions
    ,   clic_opt_add_t  : '<fmt:message key="formbuilder.clic_opt_add_t"/>'
    ,   clic_opt_del_t  : '<fmt:message key="formbuilder.clic_opt_del_t"/>'
    ,   clic_option_chs : '<fmt:message key="formbuilder.clic_option_chs"/>'
    ,   option_prompt   : '<fmt:message key="formbuilder.option_prompt"/>'
    ,   option_not_uniq : '<fmt:message key="formbuilder.option_not_uniq"/>'
        // _t : titles
    ,   clic_radio_add_t: '<fmt:message key="formbuilder.clic_radio_add_t"/>'
    ,   clic_radio_del_t: '<fmt:message key="formbuilder.clic_radio_del_t"/>'
    ,   clic_cb_add_t   : '<fmt:message key="formbuilder.clic_cb_add_t"/>'
    ,   clic_cb_del_t   : '<fmt:message key="formbuilder.clic_cb_del_t"/>'
    ,   clic_option_add : '<fmt:message key="formbuilder.clic_option_add"/>'
    ,   clic_option_del : '<fmt:message key="formbuilder.clic_option_del"/>'
    ,   clic_option_value     : '<fmt:message key="formbuilder.clic_option_value"/>'
    ,   clic_option_label     : '<fmt:message key="formbuilder.clic_option_label"/>'
    ,   clic_radio_add  : '<fmt:message key="formbuilder.clic_radio_add"/>'
    ,   clic_radio_del  : '<fmt:message key="formbuilder.clic_radio_del"/>'
    ,   clic_cb_add     : '<fmt:message key="formbuilder.clic_cb_add"/>'
    ,   clic_cb_del     : '<fmt:message key="formbuilder.clic_cb_del"/>'
    ,   clic_edit       : '<fmt:message key="formbuilder.clic_edit"/>'
};

